/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatascelulares;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author Invited
 */
public class Automatas extends javax.swing.JFrame {

    /**
     * Creates new form Ajustes
     */
    
    public Automatas() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumRegla = new javax.swing.JLabel();
        lblTamLapiz = new javax.swing.JLabel();
        txtNumRegla = new javax.swing.JTextField();
        txtTamLapiz = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btbAceptar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumRegla.setText("Numero de la regla a simular:");

        lblTamLapiz.setText("Tamaño del lapiz:");

        txtNumRegla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumReglaActionPerformed(evt);
            }
        });

        txtTamLapiz.setToolTipText("");

        jLabel3.setText("Simulacioón Automatas Celulares y Ciclo de la Vida");

        btbAceptar.setText("Aceptar");
        btbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumRegla)
                    .addComponent(lblTamLapiz))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btbAceptar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNumRegla)
                        .addComponent(txtTamLapiz, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumRegla)
                    .addComponent(txtNumRegla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTamLapiz)
                    .addComponent(txtTamLapiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btbAceptar)
                .addGap(30, 30, 30))
        );

        btbAceptar.getAccessibleContext().setAccessibleName("btnAceptar");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbAceptarActionPerformed
        Regla reg= new Regla();
        int n=Integer.parseInt( this.getTxtTamLapiz().getText());
        reg.numero=Integer.parseInt(getTxtNumRegla().getText());
        reg.simulacion(n);
        this.setVisible(false);
    }//GEN-LAST:event_btbAceptarActionPerformed

    private void txtNumReglaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumReglaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumReglaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Automatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Automatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Automatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Automatas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Automatas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbAceptar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNumRegla;
    private javax.swing.JLabel lblTamLapiz;
    private javax.swing.JTextField txtNumRegla;
    private javax.swing.JTextField txtTamLapiz;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtNumRegla() {
        return txtNumRegla;
    }

    public JTextField getTxtTamLapiz() {
        return txtTamLapiz;
    }

    
}
